### ISSUE TITLE
Form reload upon save

### ISSUE THREAD

**Issue by ChristinaR** [13pixlar/gravity-forms-sticky-form#1]
Hi - 

I am created a page that includes a sticky form that will be used for Members to create a What's in their Golf Bag Equipment Page, Like an Equipment Profile page.

How does it work from the front end with Users? Example, I changed the Submit button to Save but, when that is clicked I get the thank you your form has been submitted message. How do I keep the form there. I was under the impression that's what tis plugin does? 

Thanks!
Christina

**Comment by nineyards** [comment]
No, this plugin does not reload the form when submitted, it populates the form with the previous submission and allows for updating that submission. 

Gravity Forms hides the form after submission until you reload the page. To change this behavior you could redirect to the form page instead of displaying a confirmation message. Under confirmations for that form; check "redirect" and select the forms page.

**Comment by 13pixlar** [comment]
No, this plugin does not reload the form when submitted, it populates the form with the previous submission and allows for updating that submission.

Gravity Forms hides the form after submission until you reload the page. To change this behavior you could redirect to the form page instead of displaying a confirmation message. Under confirmations for that form; check "redirect" and select the forms page.

**Comment by ChristinaR** [comment]
It loses all its formatting which is the important part. Do you know 
of ANY plugin that will do what I need? it is essentially the firm 
fields I need without the submit feature.

Thanks!
Christina

**Comment by 13pixlar** [comment]
Im not sure what you mean by "its formatting"?

**Comment by ChristinaR** [comment]
Hi -

Please see attached. I want it to display their entered fields when 
Save button is clicked to maintain page formatting. Not sure how to 
get that done.

THanks!
Christina

**Comment by 13pixlar** [comment]
Im not sure what yopu mean by "page formatting". Try this:
1. Make sure Sticky Form is activated
2. In form settings, at the bottom, make sure "Make this form Sticky" is checked
3. In confirmations settings for that form, edit the default confirmation and set Confirmation Type to "page"
4. Select the page that has the form and hit save.
5. Test the form on the front end.
